---
- name: Configure Postgresql - allow access to todo app EC2 instance
  hosts: database
  gather_facts: yes
  vars:
    todo_public_ip: "{{ groups['todo'][0] }}"
    todo_private_ip: "{{ hostvars[ lookup('ansible.builtin.vars', 'todo_public_ip') ]['private_ip_address'] }}"
    ansible_user: ubuntu
    ansible_ssh_common_args: >-
      -o ProxyCommand="ssh -W %h:%p -l ubuntu {{ todo_public_ip }} -i /home/rafal/todo_app-hcp_vault/todo-private.key"
      -o IdentityFile="/home/rafal/todo_app-hcp_vault/todo-private.key"
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"
    - name: Listen all in postgresql.conf
      lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        firstmatch: yes
        state: present
        backup: yes
      loop:
        - { regexp: '^listen_addresses', line: "listen_addresses = '*'"}
      become: true         
    - name: allow todo app connect in pg_hba.conf
      lineinfile:
        path: /etc/postgresql/15/main/pg_hba.conf
        insertafter: "^# IPv4 local connections:"
        line: "{{ item.line }}"
        firstmatch: yes
        state: present
        backup: yes
      loop:
        - { line: "host    all             all             {{ todo_private_ip }}/32           md5"}
      become: true
    - name: Restart postgresql
      shell: sudo systemctl restart postgresql.service
      args:
        executable: /bin/bash
